# Logging Configuration
logging:
  level:
    ROOT: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    com.mycompany.myapp: DEBUG

# Spring DevTools (Development Tools) Configuration
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # We use Webpack dev server + BrowserSync for live reload

  # Jackson (JSON) Configuration
  jackson:
    serialization:
      indent-output: true

  # DataSource Configuration (PostgreSQL in this case)
  datasource:
    url: jdbc:postgresql://localhost:5432/piyush
    username: piyush
    password: Jaibalaji@28

  # JPA (Java Persistence API) Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the schema to match your entities (use "none" for manual schema management)
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true  # Show SQL statements in the log for debugging

  # Mail Configuration (for sending emails)
  mail:
    host: localhost
    port: 25
    username: 
    password:

  # Messages Configuration (Cache Duration for Messages)
  messages:
    cache-duration: PT1S # 1 second, per ISO 8601 standard

  # Thymeleaf Configuration
  thymeleaf:
    cache: false  # Disable caching for Thymeleaf templates in dev mode

# Server Configuration
server:
  port: 8080
  forward-headers-strategy: native
