options:
  logging: CLOUD_LOGGING_ONLY  # Enable Cloud Logging. Set to NONE if you don't want logs.

steps:
  # Step 1: Checkout the repository (if not already cloned)
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/p1yushsharma/jj.git']

  # Step 2: Remove any ESLint-related files (if present)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['bash', '-c', 'rm -f .eslintrc.js .eslintrc.json .eslintignore || true']

  # Step 3: Build the application using Maven
  - name: 'maven:latest'
    entrypoint: 'mvn'  # Explicitly use 'mvn' as the entrypoint
    args: ['clean', 'package', '-DskipTests']  # Run Maven with clean and package goals

  # Step 4: Deploy to Google App Engine (using the app.yaml)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'app'
      - 'deploy'
      - '--quiet'  # Deploy without asking for confirmation

# Substitutions (Optional: replace with your actual project ID)
substitutions:
  _PROJECT_ID: 'vigilant-quanta-442411-q8'  # Replace with your actual project ID

# Timeout for the entire build process
timeout: '1200s'

# Optionally, define a `env.yaml` with environment variables if needed
