# cloudbuild.yaml
steps:
  # Step 1: Checkout the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/p1yushsharma/jj.git']

  # Step 2: Build the application with Maven
  - name: 'gcr.io/cloud-builders/maven'
    args: ['clean', 'package', '-DskipTests']

  # Step 3: Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'app'
      - 'deploy'
      - '--quiet'

# Timeout settings (optional)
timeout: 1600s

# Substitutions for dynamic variables (optional)
substitutions:
  _PROJECT_ID: 'vigilant-quanta-442411-q8'
  _REGION: 'us-central1'
