options:
  logging: CLOUD_LOGGING_ONLY  

steps:

  - name: 'maven:latest'
    entrypoint: 'mvn' 
    args: ['clean', 'package', '-DskipTests']  
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'app'
      - 'deploy'
      - '--quiet'  

substitutions:
  _PROJECT_ID: 'vigilant-quanta-442411-q8' 


timeout: '1200s'

